- id: swiftlint
  name   : swiftlint
  description: Format swift code with swiftlint.
  language: system
  files: \.(swift)$
  entry: swiftlint autocorrect
  args: []

- id: bazel
  name: bazel
  description: Format WORKSPACE, BUILD, BUILD.bazel and .bzl with buildifier
  language: system
  files: (WORKSPACE|BUILD|BUILD\.bazel|\.bzl)$
  entry: buildifier
  args: []
