- id: swiftlint
  name   : swiftlint
  description: Format swift code with swiftlint.
  language: system
  files: \.(swift)$
  entry: swiftlint autocorrect
  args: []

- id: bazel
  name: bazel
  description: Format BUILD, BUILD.bazel and .bzl with buildifier
  language: system
  files: (BUILD|BUILD\.bazel|\.(bazel|bzl))$
  entry: buildifier
  args: []
